### ISSUE TITLE
Экспорт падает на одном из чатов:

### ISSUE THREAD

**Issue by alff0x1f** [zenwarr/vk-dialogue-export#12]
Запускал второй раз, так же падает

```
1 of 743   [#########           ] (23393 / 51966)Traceback (most recent call last):v845221032/da2fc/VZmLcDERF_U.jpg -> 456247477.jpg
  File "vk-dialog-export.py", line 70, in <module>
    exported_data = format_exporter.export(exported_json, progress)
  File "/home/user/vk/messages/vk-dialogue-export/html_exporter.py", line 70, in export
    ctx.output.append(self.export_message(ctx, msg))
  File "/home/user/vk/messages/vk-dialogue-export/html_exporter.py", line 146, in export_message
    return self.export_action_message(ctx, msg)
  File "/home/user/vk/messages/vk-dialogue-export/html_exporter.py", line 140, in export_action_message
    'message': self.get_action_text(ctx, msg, msg['action'], msg.get('action_text', ''), msg.get('action_mid', None)),
  File "/home/user/vk/messages/vk-dialogue-export/html_exporter.py", line 108, in get_action_text
    return 'Kicked user <span class="new-chat-title">{name}</span>'.format(name=ctx.input_json['users'].get(action_mid)['name'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by alff0x1f** [comment]
При этом с ключем `--format=json` скачивает и сохраняет нормально.

**Comment by alff0x1f** [comment]
Починил так:

```diff
diff --git a/html_exporter.py b/html_exporter.py
index e4c0a06..fad0a2d 100644
--- a/html_exporter.py
+++ b/html_exporter.py
@@ -104,8 +104,10 @@ class HTMLExporter:
                 return 'Kicked user'
             elif action_mid == msg['sender']['id']:
                 return 'Left the chat'
-            else:
+            elif action_mid in ctx.input_json['users']:
                 return 'Kicked user <span class="new-chat-title">{name}</span>'.format(name=ctx.input_json['users'].get(action_mid)['name'])
+            else:
+                return 'Kicked user'
         else:
             return action_text_dict.get(action, '')
```

Ещё у меня в html не написано кого пригласили.

> Фамилия Имя : Invited user to the chat
> Фамилия Имя : Invited user to the chat

**Comment by namikiri** [comment]
#10 #11 

issue не читай
@
issue создавай

**Comment by alff0x1f** [comment]
Сорян
@namikiri зато починил более адекватно, чем обренуть все в try / except

**Comment by alff0x1f** [comment]
Там косяк в том что пользователя которого выгнали, уже нет в чате. А словарь имен только тех, кто есть в чате.

**Comment by namikiri** [comment]
С корректностью решения @alff0x1f спорить не стану, я с пихтоном не знаком. Может PR сделаешь?

**Comment by Stat1cV01D** [comment]
Я полагаю, что при экспорте сообщения просто забыли, добавить пользователя, которого кикнули. 

Т.к. это не переписка между двумя людьми, а действие одного по отношению к другому, то и поля используются разные - см. [VK Message object](https://vk.com/dev/objects/message), объект 'action' c полем 'member_id' для таких случаев.

Я у себя сделал так, но не тестировал ещё:
```
        if 'action' in vk_msg:
            exported_msg['action'] = vk_msg['action']
            if 'member_id' in vk_msg['action']:
                ctx.add_user(vk_msg['action']['member_id'], self)
```

**Comment by zenwarr** [comment]
Исправлено в https://github.com/zenwarr/vk-dialogue-export/commit/5624a7846eead0cd2e0e839245a47f3b5a0cd3a9
